// Your current application logic...

const AUTH0_DOMAIN = 'dev-po0nbyisii0o3jk8.us.auth0.com';
const AUTH0_CLIENT_ID = 'Ksbj7Z7sDxgUjShmHK1ayrAGh0exYugZ';

// Continue with the rest of your application logic...