// ============================================================
// BI Command Center — Sample Data
// ============================================================

const DATA = {

  // ── Overview ──────────────────────────────────────────────
  overview: {
    overallScore: 34,
    architectureProgress: 42,
    adoptionProgress: 18,
    metrics: [
      { id: 'domains_live',     label: 'Domains Live & Adopted', value: 0,    unit: '',   icon: 'layers',  delta: '+1 this quarter' },
      { id: 'models_certified', label: 'Certified Semantic Models', value: 1, unit: '',   icon: 'cube',    delta: 'Target: 5' },
      { id: 'github_pct',       label: 'Models Under Version Control', value: 20, unit: '%', icon: 'git',  delta: '1 of 5 repos' },
      { id: 'hours_saved',      label: 'Monthly Hours Saved', value: 12,      unit: 'h',  icon: 'clock',   delta: '+4 vs last month' },
    ]
  },

  // ── Domains ────────────────────────────────────────────────
  domains: [
    {
      id: 'consulting',
      name: 'Consulting',
      color: '#0C67B1',
      phase: 'Building Semantic Model',
      score: 55,
      status: 'on_track',
      note: 'Semantic model V1 in progress; fact table finalized.',
      starSchema: 60,
      semanticModel: 45,
      githubReady: 30,
      adoption: 10,
      businessValue: 15,
    },
    {
      id: 'labor',
      name: 'Labor / Headcount',
      color: '#2C8ED6',
      phase: 'Designing Star Schema',
      score: 38,
      status: 'on_track',
      note: 'PII separation design complete; schema in review.',
      starSchema: 50,
      semanticModel: 20,
      githubReady: 15,
      adoption: 5,
      businessValue: 8,
    },
    {
      id: 'non_labor',
      name: 'Non-Labor',
      color: '#3B82F6',
      phase: 'Not Started',
      score: 10,
      status: 'at_risk',
      note: 'Dependency on Consulting model completion.',
      starSchema: 10,
      semanticModel: 0,
      githubReady: 0,
      adoption: 0,
      businessValue: 0,
    },
    {
      id: 'chargebacks',
      name: 'Chargebacks',
      color: '#6366F1',
      phase: 'Not Started',
      score: 8,
      status: 'at_risk',
      note: 'Awaiting source system mapping from Finance Ops.',
      starSchema: 8,
      semanticModel: 0,
      githubReady: 0,
      adoption: 0,
      businessValue: 0,
    },
    {
      id: 'consolidation',
      name: 'Consolidation',
      color: '#8B5CF6',
      phase: 'Not Started',
      score: 5,
      status: 'at_risk',
      note: 'Planned for H2; requires all domain models complete.',
      starSchema: 5,
      semanticModel: 0,
      githubReady: 0,
      adoption: 0,
      businessValue: 0,
    },
  ],

  // ── Power BI Models ────────────────────────────────────────
  models: [
    {
      id: 'consulting_sem',
      title: 'Expense_Consulting_Semantic',
      domain: 'Consulting',
      inGithub: true,
      docPct: 65,
      validationStatus: 'Core checks passing',
      validationChip: 'green',
      deployStatus: 'In Development',
      deployChip: 'yellow',
      version: 'v0.8',
    },
    {
      id: 'labor_sem',
      title: 'Expense_Labor_Semantic',
      domain: 'Labor / Headcount',
      inGithub: false,
      docPct: 30,
      validationStatus: 'Schema validation pending',
      validationChip: 'yellow',
      deployStatus: 'Designing',
      deployChip: 'grey',
      version: 'v0.2',
    },
    {
      id: 'nonlabor_sem',
      title: 'Expense_NonLabor_Semantic',
      domain: 'Non-Labor',
      inGithub: false,
      docPct: 0,
      validationStatus: 'Not started',
      validationChip: 'grey',
      deployStatus: 'Not Started',
      deployChip: 'grey',
      version: '—',
    },
    {
      id: 'chargebacks_sem',
      title: 'Expense_Chargebacks_Semantic',
      domain: 'Chargebacks',
      inGithub: false,
      docPct: 0,
      validationStatus: 'Not started',
      validationChip: 'grey',
      deployStatus: 'Not Started',
      deployChip: 'grey',
      version: '—',
    },
    {
      id: 'consolidation_sem',
      title: 'Expense_Consolidation_Semantic',
      domain: 'Consolidation',
      inGithub: false,
      docPct: 0,
      validationStatus: 'Not started',
      validationChip: 'grey',
      deployStatus: 'Not Started',
      deployChip: 'grey',
      version: '—',
    },
  ],

  // ── GitHub / CI-CD ─────────────────────────────────────────
  github: {
    repoCount: 3,
    recentCommits: 27,
    openPRs: 2,
    pipelines: [
      { name: 'expense-consulting-pbi', status: 'Pipeline Defined', chip: 'blue',   tests: 'Partial', deploy: 'Manual' },
      { name: 'expense-labor-pbi',      status: 'In Progress',      chip: 'yellow', tests: 'None',    deploy: 'None' },
      { name: 'bi-infra-shared',        status: 'Active',           chip: 'green',  tests: 'Core',    deploy: 'Automated' },
    ],
    activity: [4, 2, 7, 3, 8, 5, 9, 2, 6, 4, 11, 8, 3, 7, 9, 12, 6, 4, 8, 5, 10, 7, 3, 9, 11, 6, 8],
    ciChecklist: [
      { label: 'Repo naming convention',       done: true },
      { label: 'Branch protection rules',       done: true },
      { label: '.pbip format committed',        done: true },
      { label: 'CI pipeline defined (YAML)',    done: true },
      { label: 'Automated schema validation',   done: false },
      { label: 'Deployment automation',         done: false },
      { label: 'Rollback strategy defined',     done: false },
      { label: 'Code review process in place',  done: true },
    ],
  },

  // ── Impact & Value ─────────────────────────────────────────
  impact: {
    hoursSaved: 12,
    forecastStepsReduced: 6,
    vendorCostAvoided: 28000,
    milestones: [
      { title: 'Consulting Star Schema Finalized',    date: 'Jan 2026', status: 'done',   desc: 'Fact + 6 dimension tables designed and documented.' },
      { title: 'First Power BI Model in GitHub',      date: 'Feb 2026', status: 'done',   desc: 'Consulting semantic model committed in .pbip format.' },
      { title: 'Tech Finance Pilot Self-Service',     date: 'Q2 2026',  status: 'active', desc: 'Pilot deployment with Tech Finance stakeholders.' },
      { title: 'Labor PII Separation Secured',        date: 'Q2 2026',  status: 'active', desc: 'PII data separated; row-level security designed.' },
      { title: 'First Exec Demo – Full Platform',     date: 'Q3 2026',  status: '',       desc: 'End-to-end demo across 3 domains for BI leadership.' },
      { title: 'All 5 Domains Live',                  date: 'Q4 2026',  status: '',       desc: 'All semantic models deployed and adopted by finance.' },
    ],
    monthlyHours: [0, 2, 2, 4, 6, 8, 8, 12, 12, 0, 0, 0],
  },

  // ── Skills ─────────────────────────────────────────────────
  skills: [
    { name: 'BI Architecture',         level: 'Intermediate', levelPct: 60, targetPct: 95, color: '#0C67B1' },
    { name: 'Power BI Engineering',    level: 'Intermediate', levelPct: 55, targetPct: 95, color: '#2C8ED6' },
    { name: 'GitHub / CI-CD for BI',   level: 'Beginner',     levelPct: 30, targetPct: 90, color: '#3B82F6' },
    { name: 'Data Governance',         level: 'Intermediate', levelPct: 50, targetPct: 90, color: '#6366F1' },
    { name: 'Self-Service Enablement', level: 'Beginner',     levelPct: 25, targetPct: 95, color: '#8B5CF6' },
    { name: 'Executive Storytelling',  level: 'Advanced',     levelPct: 75, targetPct: 95, color: '#0C67B1' },
  ],
  skillMilestones: [
    { date: 'Dec 2025', title: 'Designed multi-domain expense star schema',                    status: 'done' },
    { date: 'Jan 2026', title: 'Implemented first Power BI deployment via GitHub (.pbip)',     status: 'done' },
    { date: 'Feb 2026', title: 'Built row-level security model for Labor PII data',            status: 'done' },
    { date: 'Q2 2026',  title: 'Ran self-service training with Finance partners',              status: 'active' },
    { date: 'Q2 2026',  title: 'Published certified Consulting semantic model',                status: 'active' },
    { date: 'Q3 2026',  title: 'Completed GitHub CI/CD automation for all 5 models',          status: '' },
    { date: 'Q4 2026',  title: 'Presented full platform to VP-level audience',                status: '' },
    { date: '2027',     title: 'Recognized as top 0.1% Director of BI – Expense Technology',  status: '' },
  ],
};
